name: Python package

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6]
    name: Python ${{ matrix.python-version }} example
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
#      - name: Setup tmate session
#        uses: mxschmitt/action-tmate@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest poetry pytest-resource-path nbmake pytest-parallel poetry
          conda install -c conda-forge theano=1.0.5
          pip install --upgrade https://github.com/Lasagne/Lasagne/archive/master.zip
      - name: Install dependencies
        run: |
          make full
      - name: Test with pytest
        run: |
          make test